apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: test-scheduler
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: sample-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: sample-scheduler
      lockObjectNamespace: kube-system
    plugins:
      preFilter:
        enabled:
        - name: "sample-plugins"
      filter:
        enabled:
        - name: "sample-plugins"
      preBind:
        enabled:
        - name: "sample-plugins"
    pluginConfig:
    - name: "sample-plugins"
      args:
        favorite_color: "#326CE5"
        favorite_number: 7
        thanks_to: "tianshimoyi"
