apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-scheduler
  namespace: test-scheduler

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-scheduler
  namespace: test-scheduler
  [root@infra1002v rbac]# cat clusterrolebinding.yaml
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: sample-scheduler
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: sample-scheduler
          namespace: test-scheduler
